class Error(RuntimeError): ...
class TensorError(Error): ...
class ShapeError(TensorError): ...
class DTypeError(TensorError): ...
class DeviceError(TensorError): ...
class ReadOnlyError(TensorError): ...
class ExecutionError(Error): ...
