from typing import Any, List

import numpy as np
from numpy.typing import ArrayLike, NDArray


class OneHotEncoder:
    handle_unknown: str
    categories_: List[NDArray[Any]]
    n_features_in_: int
    n_features_out_: int

    def __init__(self, handle_unknown: str) -> None: ...
    def fit(self, X: ArrayLike) -> None: ...
    def transform(self, X: ArrayLike) -> NDArray[np.float64]: ...
    def fit_transform(self, X: ArrayLike) -> NDArray[np.float64]: ...
    def inverse_transform(self, X: ArrayLike) -> NDArray[Any]: ...
    def state_dict(self) -> dict: ...
    def load_state_dict(self, state: dict) -> None: ...


class OrdinalEncoder:
    handle_unknown: str
    unknown_value: float
    categories_: List[NDArray[Any]]
    n_features_in_: int

    def __init__(
        self,
        handle_unknown: str,
        unknown_value: float,
    ) -> None: ...
    def fit(self, X: ArrayLike) -> None: ...
    def transform(self, X: ArrayLike) -> NDArray[np.float64]: ...
    def fit_transform(self, X: ArrayLike) -> NDArray[np.float64]: ...
    def inverse_transform(self, X: ArrayLike) -> NDArray[Any]: ...
    def state_dict(self) -> dict: ...
    def load_state_dict(self, state: dict) -> None: ...
