from typing import Any, Optional, Sequence, Tuple

import numpy as np

from .dtype import DType


class Tensor:
    def __init__(self, data: Any, copy: Optional[bool] = ...) -> None: ...

    @property
    def shape(self) -> Tuple[int, ...]: ...
    @property
    def strides(self) -> Tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def dtype(self) -> DType: ...
    @property
    def device(self) -> str: ...
    @property
    def writable(self) -> bool: ...
    @property
    def is_contiguous(self) -> bool: ...
    @property
    def is_fortran_contiguous(self) -> bool: ...
    @property
    def T(self) -> Tensor: ...

    def numpy(self, copy: bool = ...) -> np.ndarray: ...
    def clone(self) -> Tensor: ...
    def contiguous(self) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, dimension0: int = ..., dimension1: int = ...) -> Tensor: ...
    def __array__(
        self,
        dtype: Optional[Any] = ...,
        copy: Optional[bool] = ...,
    ) -> np.ndarray: ...
    def __add__(self, other: Tensor) -> Tensor: ...
    def __sub__(self, other: Tensor) -> Tensor: ...
    def __mul__(self, other: Tensor) -> Tensor: ...
    def __truediv__(self, other: Tensor) -> Tensor: ...
